[package]

name = "redox"
version = "0.0.1"
authors = [
    "bvssvni <bvssvni@gmail.com>"
]

[[bin]]

name = "redox"
path = "src/main.rs"

[dependencies]
iron = "0.2.2"
hyper = "*" # anything that goes with Iron
postgres = "0.9.6"
staticfile = "*" # anything that goes with Iron
mount = "*" # anything that goes with Iron
